# Generated by Django 2.2.9 on 2020-03-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200128_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('apartment', models.IntegerField(blank=True, null=True)),
                ('residents', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_brand_1', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_model_1', models.CharField(blank=True, max_length=30, null=True)),
                ('license_plate_1', models.CharField(blank=True, max_length=8, null=True)),
                ('vehicle_brand_2', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_model_2', models.CharField(blank=True, max_length=30, null=True)),
                ('license_plate_2', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'Propretário',
                'verbose_name_plural': 'Proprietários',
                'db_table': 'apartment_owner',
            },
        ),
        migrations.CreateModel(
            name='OwnerContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contratos',
                'db_table': 'owner_contract_type',
            },
        ),
        migrations.CreateModel(
            name='OwnerSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
                'db_table': 'owner_situation',
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'db_table': 'tower',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Veiculo',
                'verbose_name_plural': 'Tipos de Veiculos',
                'db_table': 'vehicle_type',
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='owner',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.OwnerContractType'),
        ),
        migrations.AddField(
            model_name='owner',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.OwnerSituation'),
        ),
        migrations.AddField(
            model_name='owner',
            name='tower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tower'),
        ),
        migrations.AddField(
            model_name='owner',
            name='vehicle_type_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle_type_1', to='core.VehicleType'),
        ),
        migrations.AddField(
            model_name='owner',
            name='vehicle_type_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle_type_2', to='core.VehicleType'),
        ),
    ]
