# Generated by Django 2.2.9 on 2020-03-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200303_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phone',
        ),
        migrations.AddField(
            model_name='owner',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
