# Generated by Django 2.2.9 on 2020-03-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200305_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='notes',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
